export const countries = [
    { code: 'ES', label_en: 'Spain', label_es: 'España', phone: '34', suggested: true },
    { code: 'AF', label_en: 'Afghanistan', label_es: 'Afganistán', phone: '93' },
    { code: 'AL', label_en: 'Albania', label_es: 'Albania', phone: '355' },
    { code: 'DZ', label_en: 'Algeria', label_es: 'Argelia', phone: '213' },
    { code: 'AD', label_en: 'Andorra', label_es: 'Andorra', phone: '376' },
    { code: 'AO', label_en: 'Angola', label_es: 'Angola', phone: '244' },
    { code: 'AG', label_en: 'Antigua and Barbuda', label_es: 'Antigua y Barbuda', phone: '1' },
    { code: 'AR', label_en: 'Argentina', label_es: 'Argentina', phone: '54' },
    { code: 'AM', label_en: 'Armenia', label_es: 'Armenia', phone: '374' },
    { code: 'AU', label_en: 'Australia', label_es: 'Australia', phone: '61' },
    { code: 'AT', label_en: 'Austria', label_es: 'Austria', phone: '43' },
    { code: 'AZ', label_en: 'Azerbaijan', label_es: 'Azerbaiyán', phone: '994' },
    { code: 'BS', label_en: 'Bahamas', label_es: 'Bahamas', phone: '1' },
    { code: 'BH', label_en: 'Bahrain', label_es: 'Baréin', phone: '973' },
    { code: 'BD', label_en: 'Bangladesh', label_es: 'Bangladés', phone: '880' },
    { code: 'BB', label_en: 'Barbados', label_es: 'Barbados', phone: '1' },
    { code: 'BY', label_en: 'Belarus', label_es: 'Bielorrusia', phone: '375' },
    { code: 'BE', label_en: 'Belgium', label_es: 'Bélgica', phone: '32' },
    { code: 'BZ', label_en: 'Belize', label_es: 'Belice', phone: '501' },
    { code: 'BJ', label_en: 'Benin', label_es: 'Benín', phone: '229' },
    { code: 'BT', label_en: 'Bhutan', label_es: 'Bután', phone: '975' },
    { code: 'BO', label_en: 'Bolivia', label_es: 'Bolivia', phone: '591' },
    { code: 'BA', label_en: 'Bosnia and Herzegovina', label_es: 'Bosnia y Herzegovina', phone: '387' },
    { code: 'BW', label_en: 'Botswana', label_es: 'Botsuana', phone: '267' },
    { code: 'BR', label_en: 'Brazil', label_es: 'Brasil', phone: '55' },
    { code: 'BN', label_en: 'Brunei', label_es: 'Brunéi', phone: '673' },
    { code: 'BG', label_en: 'Bulgaria', label_es: 'Bulgaria', phone: '359' },
    { code: 'BF', label_en: 'Burkina Faso', label_es: 'Burkina Faso', phone: '226' },
    { code: 'BI', label_en: 'Burundi', label_es: 'Burundi', phone: '257' },
    { code: 'KH', label_en: 'Cambodia', label_es: 'Camboya', phone: '855' },
    { code: 'CM', label_en: 'Cameroon', label_es: 'Camerún', phone: '237' },
    { code: 'CA', label_en: 'Canada', label_es: 'Canadá', phone: '1' },
    { code: 'CV', label_en: 'Cape Verde', label_es: 'Cabo Verde', phone: '238' },
    { code: 'CF', label_en: 'Central African Republic', label_es: 'República Centroafricana', phone: '236' },
    { code: 'TD', label_en: 'Chad', label_es: 'Chad', phone: '235' },
    { code: 'CL', label_en: 'Chile', label_es: 'Chile', phone: '56' },
    { code: 'CN', label_en: 'China', label_es: 'China', phone: '86' },
    { code: 'CO', label_en: 'Colombia', label_es: 'Colombia', phone: '57' },
    { code: 'KM', label_en: 'Comoros', label_es: 'Comoras', phone: '269' },
    { code: 'CG', label_en: 'Congo', label_es: 'Congo', phone: '242' },
    { code: 'CR', label_en: 'Costa Rica', label_es: 'Costa Rica', phone: '506' },
    { code: 'HR', label_en: 'Croatia', label_es: 'Croacia', phone: '385' },
    { code: 'CU', label_en: 'Cuba', label_es: 'Cuba', phone: '53' },
    { code: 'CY', label_en: 'Cyprus', label_es: 'Chipre', phone: '357' },
    { code: 'CZ', label_en: 'Czech Republic', label_es: 'República Checa', phone: '420' },
    { code: 'DK', label_en: 'Denmark', label_es: 'Dinamarca', phone: '45' },
    { code: 'DJ', label_en: 'Djibouti', label_es: 'Yibuti', phone: '253' },
    { code: 'DM', label_en: 'Dominica', label_es: 'Dominica', phone: '1' },
    { code: 'DO', label_en: 'Dominican Republic', label_es: 'República Dominicana', phone: '1' },
    { code: 'EC', label_en: 'Ecuador', label_es: 'Ecuador', phone: '593' },
    { code: 'EG', label_en: 'Egypt', label_es: 'Egipto', phone: '20' },
    { code: 'SV', label_en: 'El Salvador', label_es: 'El Salvador', phone: '503' },
    { code: 'GQ', label_en: 'Equatorial Guinea', label_es: 'Guinea Ecuatorial', phone: '240' },
    { code: 'ER', label_en: 'Eritrea', label_es: 'Eritrea', phone: '291' },
    { code: 'EE', label_en: 'Estonia', label_es: 'Estonia', phone: '372' },
    { code: 'ET', label_en: 'Ethiopia', label_es: 'Etiopía', phone: '251' },
    { code: 'FJ', label_en: 'Fiji', label_es: 'Fiyi', phone: '679' },
    { code: 'FI', label_en: 'Finland', label_es: 'Finlandia', phone: '358' },
    { code: 'FR', label_en: 'France', label_es: 'Francia', phone: '33', suggested: true },
    { code: 'GA', label_en: 'Gabon', label_es: 'Gabón', phone: '241' },
    { code: 'GM', label_en: 'Gambia', label_es: 'Gambia', phone: '220' },
    { code: 'GE', label_en: 'Georgia', label_es: 'Georgia', phone: '995' },
    { code: 'DE', label_en: 'Germany', label_es: 'Alemania', phone: '49', suggested: true },
    { code: 'GH', label_en: 'Ghana', label_es: 'Ghana', phone: '233' },
    { code: 'GR', label_en: 'Greece', label_es: 'Grecia', phone: '30' },
    { code: 'GD', label_en: 'Grenada', label_es: 'Granada', phone: '1' },
    { code: 'GT', label_en: 'Guatemala', label_es: 'Guatemala', phone: '502' },
    { code: 'GN', label_en: 'Guinea', label_es: 'Guinea', phone: '224' },
    { code: 'GW', label_en: 'Guinea-Bissau', label_es: 'Guinea-Bisáu', phone: '245' },
    { code: 'GY', label_en: 'Guyana', label_es: 'Guyana', phone: '592' },
    { code: 'HT', label_en: 'Haiti', label_es: 'Haití', phone: '509' },
    { code: 'HN', label_en: 'Honduras', label_es: 'Honduras', phone: '504' },
    { code: 'HU', label_en: 'Hungary', label_es: 'Hungría', phone: '36' },
    { code: 'IS', label_en: 'Iceland', label_es: 'Islandia', phone: '354' },
    { code: 'IN', label_en: 'India', label_es: 'India', phone: '91' },
    { code: 'ID', label_en: 'Indonesia', label_es: 'Indonesia', phone: '62' },
    { code: 'IR', label_en: 'Iran', label_es: 'Irán', phone: '98' },
    { code: 'IQ', label_en: 'Iraq', label_es: 'Irak', phone: '964' },
    { code: 'IE', label_en: 'Ireland', label_es: 'Irlanda', phone: '353' },
    { code: 'IL', label_en: 'Israel', label_es: 'Israel', phone: '972' },
    { code: 'IT', label_en: 'Italy', label_es: 'Italia', phone: '39' },
    { code: 'JM', label_en: 'Jamaica', label_es: 'Jamaica', phone: '1' },
    { code: 'JP', label_en: 'Japan', label_es: 'Japón', phone: '81' },
    { code: 'JO', label_en: 'Jordan', label_es: 'Jordania', phone: '962' },
    { code: 'KZ', label_en: 'Kazakhstan', label_es: 'Kazajistán', phone: '7' },
    { code: 'KE', label_en: 'Kenya', label_es: 'Kenia', phone: '254' },
    { code: 'KI', label_en: 'Kiribati', label_es: 'Kiribati', phone: '686' },
    { code: 'KP', label_en: 'North Korea', label_es: 'Corea del Norte', phone: '850' },
    { code: 'KR', label_en: 'South Korea', label_es: 'Corea del Sur', phone: '82' },
    { code: 'KW', label_en: 'Kuwait', label_es: 'Kuwait', phone: '965' },
    { code: 'KG', label_en: 'Kyrgyzstan', label_es: 'Kirguistán', phone: '996' },
    { code: 'LA', label_en: 'Laos', label_es: 'Laos', phone: '856' },
    { code: 'LV', label_en: 'Latvia', label_es: 'Letonia', phone: '371' },
    { code: 'LB', label_en: 'Lebanon', label_es: 'Líbano', phone: '961' },
    { code: 'LS', label_en: 'Lesotho', label_es: 'Lesoto', phone: '266' },
    { code: 'LR', label_en: 'Liberia', label_es: 'Liberia', phone: '231' },
    { code: 'LY', label_en: 'Libya', label_es: 'Libia', phone: '218' },
    { code: 'LI', label_en: 'Liechtenstein', label_es: 'Liechtenstein', phone: '423' },
    { code: 'LT', label_en: 'Lithuania', label_es: 'Lituania', phone: '370' },
    { code: 'LU', label_en: 'Luxembourg', label_es: 'Luxemburgo', phone: '352' },
    { code: 'MK', label_en: 'North Macedonia', label_es: 'Macedonia del Norte', phone: '389' },
    { code: 'MG', label_en: 'Madagascar', label_es: 'Madagascar', phone: '261' },
    { code: 'MW', label_en: 'Malawi', label_es: 'Malaui', phone: '265' },
    { code: 'MY', label_en: 'Malaysia', label_es: 'Malasia', phone: '60' },
    { code: 'MV', label_en: 'Maldives', label_es: 'Maldivas', phone: '960' },
    { code: 'ML', label_en: 'Mali', label_es: 'Malí', phone: '223' },
    { code: 'MT', label_en: 'Malta', label_es: 'Malta', phone: '356' },
    { code: 'MH', label_en: 'Marshall Islands', label_es: 'Islas Marshall', phone: '692' },
    { code: 'MR', label_en: 'Mauritania', label_es: 'Mauritania', phone: '222' },
    { code: 'MU', label_en: 'Mauritius', label_es: 'Mauricio', phone: '230' },
    { code: 'MX', label_en: 'Mexico', label_es: 'México', phone: '52' },
    { code: 'FM', label_en: 'Micronesia', label_es: 'Micronesia', phone: '691' },
    { code: 'MD', label_en: 'Moldova', label_es: 'Moldavia', phone: '373' },
    { code: 'MC', label_en: 'Monaco', label_es: 'Mónaco', phone: '377' },
    { code: 'MN', label_en: 'Mongolia', label_es: 'Mongolia', phone: '976' },
    { code: 'ME', label_en: 'Montenegro', label_es: 'Montenegro', phone: '382' },
    { code: 'MA', label_en: 'Morocco', label_es: 'Marruecos', phone: '212' },
    { code: 'MZ', label_en: 'Mozambique', label_es: 'Mozambique', phone: '258' },
    { code: 'MM', label_en: 'Myanmar', label_es: 'Myanmar', phone: '95' },
    { code: 'NA', label_en: 'Namibia', label_es: 'Namibia', phone: '264' },
    { code: 'NR', label_en: 'Nauru', label_es: 'Nauru', phone: '674' },
    { code: 'NP', label_en: 'Nepal', label_es: 'Nepal', phone: '977' },
    { code: 'NL', label_en: 'Netherlands', label_es: 'Países Bajos', phone: '31' },
    { code: 'NZ', label_en: 'New Zealand', label_es: 'Nueva Zelanda', phone: '64' },
    { code: 'NI', label_en: 'Nicaragua', label_es: 'Nicaragua', phone: '505' },
    { code: 'NE', label_en: 'Niger', label_es: 'Níger', phone: '227' },
    { code: 'NG', label_en: 'Nigeria', label_es: 'Nigeria', phone: '234' },
    { code: 'NO', label_en: 'Norway', label_es: 'Noruega', phone: '47' },
    { code: 'OM', label_en: 'Oman', label_es: 'Omán', phone: '968' },
    { code: 'PK', label_en: 'Pakistan', label_es: 'Pakistán', phone: '92' },
    { code: 'PW', label_en: 'Palau', label_es: 'Palaos', phone: '680' },
    { code: 'PA', label_en: 'Panama', label_es: 'Panamá', phone: '507' },
    { code: 'PG', label_en: 'Papua New Guinea', label_es: 'Papúa Nueva Guinea', phone: '675' },
    { code: 'PY', label_en: 'Paraguay', label_es: 'Paraguay', phone: '595' },
    { code: 'PE', label_en: 'Peru', label_es: 'Perú', phone: '51' },
    { code: 'PH', label_en: 'Philippines', label_es: 'Filipinas', phone: '63' },
    { code: 'PL', label_en: 'Poland', label_es: 'Polonia', phone: '48' },
    { code: 'PT', label_en: 'Portugal', label_es: 'Portugal', phone: '351' },
    { code: 'QA', label_en: 'Qatar', label_es: 'Catar', phone: '974' },
    { code: 'RO', label_en: 'Romania', label_es: 'Rumania', phone: '40' },
    { code: 'RU', label_en: 'Russian Federation', label_es: 'Federación Rusa', phone: '7' },
    { code: 'RW', label_en: 'Rwanda', label_es: 'Ruanda', phone: '250' },
    { code: 'KN', label_en: 'Saint Kitts and Nevis', label_es: 'San Cristóbal y Nieves', phone: '1' },
    { code: 'LC', label_en: 'Saint Lucia', label_es: 'Santa Lucía', phone: '1' },
    { code: 'VC', label_en: 'Saint Vincent and the Grenadines', label_es: 'San Vicente y las Granadinas', phone: '1' },
    { code: 'WS', label_en: 'Samoa', label_es: 'Samoa', phone: '685' },
    { code: 'SM', label_en: 'San Marino', label_es: 'San Marino', phone: '378' },
    { code: 'ST', label_en: 'Sao Tome and Principe', label_es: 'Santo Tomé y Príncipe', phone: '239' },
    { code: 'SA', label_en: 'Saudi Arabia', label_es: 'Arabia Saudita', phone: '966' },
    { code: 'SN', label_en: 'Senegal', label_es: 'Senegal', phone: '221' },
    { code: 'RS', label_en: 'Serbia', label_es: 'Serbia', phone: '381' },
    { code: 'SC', label_en: 'Seychelles', label_es: 'Seychelles', phone: '248' },
    { code: 'SL', label_en: 'Sierra Leone', label_es: 'Sierra Leona', phone: '232' },
    { code: 'SG', label_en: 'Singapore', label_es: 'Singapur', phone: '65' },
    { code: 'SK', label_en: 'Slovakia', label_es: 'Eslovaquia', phone: '421' },
    { code: 'SI', label_en: 'Slovenia', label_es: 'Eslovenia', phone: '386' },
    { code: 'SB', label_en: 'Solomon Islands', label_es: 'Islas Salomón', phone: '677' },
    { code: 'SO', label_en: 'Somalia', label_es: 'Somalia', phone: '252' },
    { code: 'ZA', label_en: 'South Africa', label_es: 'Sudáfrica', phone: '27' },
    { code: 'SS', label_en: 'South Sudan', label_es: 'Sudán del Sur', phone: '211' },
    { code: 'LK', label_en: 'Sri Lanka', label_es: 'Sri Lanka', phone: '94' },
    { code: 'SD', label_en: 'Sudan', label_es: 'Sudán', phone: '249' },
    { code: 'SR', label_en: 'Suriname', label_es: 'Surinam', phone: '597' },
    { code: 'SE', label_en: 'Sweden', label_es: 'Suecia', phone: '46' },
    { code: 'CH', label_en: 'Switzerland', label_es: 'Suiza', phone: '41' },
    { code: 'SY', label_en: 'Syria', label_es: 'Siria', phone: '963' },
    { code: 'TW', label_en: 'Taiwan', label_es: 'Taiwán', phone: '886' },
    { code: 'TJ', label_en: 'Tajikistan', label_es: 'Tayikistán', phone: '992' },
    { code: 'TZ', label_en: 'Tanzania', label_es: 'Tanzania', phone: '255' },
    { code: 'TH', label_en: 'Thailand', label_es: 'Tailandia', phone: '66' },
    { code: 'TL', label_en: 'Timor-Leste', label_es: 'Timor Oriental', phone: '670' },
    { code: 'TG', label_en: 'Togo', label_es: 'Togo', phone: '228' },
    { code: 'TO', label_en: 'Tonga', label_es: 'Tonga', phone: '676' },
    { code: 'TT', label_en: 'Trinidad and Tobago', label_es: 'Trinidad y Tobago', phone: '1' },
    { code: 'TN', label_en: 'Tunisia', label_es: 'Túnez', phone: '216' },
    { code: 'TR', label_en: 'Turkey', label_es: 'Turquía', phone: '90' },
    { code: 'TM', label_en: 'Turkmenistan', label_es: 'Turkmenistán', phone: '993' },
    { code: 'TV', label_en: 'Tuvalu', label_es: 'Tuvalu', phone: '688' },
    { code: 'UG', label_en: 'Uganda', label_es: 'Uganda', phone: '256' },
    { code: 'UA', label_en: 'Ukraine', label_es: 'Ucrania', phone: '380' },
    { code: 'AE', label_en: 'United Arab Emirates', label_es: 'Emiratos Árabes Unidos', phone: '971' },
    { code: 'GB', label_en: 'United Kingdom', label_es: 'Reino Unido', phone: '44' },
    { code: 'US', label_en: 'United States', label_es: 'Estados Unidos', phone: '1' },
    { code: 'UY', label_en: 'Uruguay', label_es: 'Uruguay', phone: '598' },
    { code: 'UZ', label_en: 'Uzbekistan', label_es: 'Uzbekistán', phone: '998' },
    { code: 'VU', label_en: 'Vanuatu', label_es: 'Vanuatu', phone: '678' },
    { code: 'VA', label_en: 'Vatican City', label_es: 'Ciudad del Vaticano', phone: '379' },
    { code: 'VE', label_en: 'Venezuela', label_es: 'Venezuela', phone: '58' },
    { code: 'VN', label_en: 'Vietnam', label_es: 'Vietnam', phone: '84' },
    { code: 'YE', label_en: 'Yemen', label_es: 'Yemen', phone: '967' },
    { code: 'ZM', label_en: 'Zambia', label_es: 'Zambia', phone: '260' },
    { code: 'ZW', label_en: 'Zimbabwe', label_es: 'Zimbabue', phone: '263' }
];
